system:
  displayName: 网上招聘系统
server:
  port: 3000
modules:
  database:
    db_host: battlehawk233.cn
    db_port: 27017
    db_name: online_hire
  fileStorage:
    endPoint: battlehawk233.cn
    port: 10000
    useSSL: false
    accessKey: admin
    secretKey: 20010428YXL.
    bucketName: online-hire
    region: online_hire
